Bikes/urls.py
from django.conf.urls import url

from Bikes import views

urlpatterns = [
    url(r'^$', views.bike_type_list, name="type"),

    url(r'superuser/$', views.admin_orders, name="all_orders"),
    url(r'superuser/message/$', views.admin_send_message, name='admin_message'),
    url(r'superuser/ready to ship/$', views.orders_ready_to_ship, name="admin_shipping"),
    url(r'superuser/mark shipped/$', views.shipping_order, name="mark shipped"),
    url(r'superuser/received/(?P<pk>\d+)/$', views.recieved_order, name="recieved"), # login not working
    url(r'superuser/(?P<pk>\d+)/$', views.admin_user_preorders, name="users_orders"),
    # url(r'superuser/bike/(?P<pk>\d+)$', views.admin_orders_bike, name="bike_ordered"),
    url(r'superuser/change amount/$', views.change_reservation_amount, name="change_reservation_amount"),

    url(r'user/$', views.users_orders, name='user'),
    # url(r'user/ready/$', views.users_orders_ready, name='ready'),
    # url(r'user/ready/(?P<pk>\d+)/$', views.ready_order_details, name='shipping'),
    # url(r'user/shipped/(?P<pk>\d+)/$', views.sending_order_details, name='shipped'),
    url(r'user/edit address/$', views.edit_address, name='edit_address'),
    url(r'user/change address/$', views.change_address, name='change_address'),
    url(r'user/edit card/$', views.edit_card, name='edit_card'),
    url(r'user/change card/$', views.change_card, name='change_card'),
    # url(r'user/edit cards/$', views.edit_cards, name='edit_cards'),
    url(r'user/(?P<pk>\d+)/$', views.order_details, name='order_detail'),
    url(r'user/edit/$', views.edit_order, name='edit'),
    # url(r'user/change password/$', views.change_password, name='change_password'),
    url(r'user/cancel order/$', views.cancel_order, name='cancel'),
    url(r'user/cancel orders/$', views.cancel_all_orders, name='cancel_all'),
    url(r'user/add address/$', views.add_address, name="add_address"),
    url(r'user/add card/$', views.add_card, name="add_card"),

    url(r'first checkout/$', views.first_checkout, name='first_checkout'),
    url(r'checkout/$', views.checkout, name='checkout'),


    url(r'^(?P<types_pk>\d+)/(?P<bike_pk>\d+)/$', views.bike_details, name='details'),
    # url(r'(?P<types_pk>\d+)/(?P<bike_pk>\d+)/order/$', views.order_bike, name='order'),
    # url(r'(?P<types_pk>\d+)/(?P<bike_pk>\d+)/order more/$', views.order_another_bike, name='order_more'),
    url(r'^(?P<pk>\d+)/$', views.bike_list, name='list'),
]

EletricBikeReserving/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

from EletricBikeReserving import views
from shopping_cart.views import register

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', views.home, name='home'),
    url(r'login/$', views.loginer, name='login'),
    url(r'accounts/login/$', views.loginer, name='login'),
    url(r'logout/$', views.logout_view, name='logout'),
    url(r'^message/$', views.message, name="message"),
    url(r'^delete message/$', views.delete_message, name="delete"),
    url(r'register/(?P<pk>\d+)/$', register, name='register'),

    url(r'^bikes/', include('Bikes.urls', namespace='bikes')),
    url(r'^cart/', include('shopping_cart.urls', namespace='cart'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Bikes/models.py
from django.core.validators import RegexValidator
from django.db import models
from djmoney.models.fields import MoneyField

# Create your models here.
from localflavor.us.models import USStateField, USZipCodeField


class BikeTypes(models.Model):
    type = models.CharField(max_length=100)
    picture = models.ImageField(upload_to='images')

    def __str__(self):
        return self.type


class Bikes(models.Model):
    type = models.ForeignKey(BikeTypes)
    name = models.CharField(max_length=100)
    picture = models.ImageField()
    description = models.TextField()
    price = MoneyField(max_digits=7,
                       decimal_places=2,
                       default_currency='USD',
                       )

    motor = models.CharField(null=True, blank=True, max_length=100)
    battery = models.CharField(null=True, blank=True, max_length=100)
    PAS = models.CharField(null=True, blank=True, max_length=100)
    controller = models.CharField(null=True, blank=True, max_length=100)
    charger = models.CharField(null=True, blank=True, max_length=100)
    charging_time = models.CharField(null=True, blank=True, max_length=100)

    max_speed = models.IntegerField(null=True, blank=True)
    range = models.IntegerField(null=True, blank=True)
    max_load = models.FloatField(null=True, blank=True)
    net_weight = models.FloatField(null=True, blank=True)
    gross_weight = models.FloatField(null=True, blank=True)
    container_load = models.FloatField(null=True, blank=True)
    display = models.CharField(null=True, blank=True, max_length=100)

    frame = models.CharField(null=True, blank=True, max_length=100)
    tyres = models.CharField(null=True, blank=True, max_length=100)
    rim = models.CharField(null=True, blank=True, max_length=100)
    front_fork = models.CharField(null=True, blank=True, max_length=100)
    front_brake = models.CharField(null=True, blank=True, max_length=100)
    rear_break = models.CharField(null=True, blank=True, max_length=100)
    speed = models.IntegerField(null=True, blank=True)
    derailleur = models.CharField(null=True, blank=True, max_length=100)
    stem = models.CharField(null=True, blank=True, max_length=100)
    brake_lever = models.CharField(null=True, blank=True, max_length=100)
    chain = models.CharField(null=True, blank=True, max_length=100)
    chain_wheel = models.CharField(null=True, blank=True, max_length=100)
    mudguard = models.CharField(null=True, blank=True, max_length=100)
    saddle = models.CharField(null=True, blank=True, max_length=100)
    pedal = models.CharField(null=True, blank=True, max_length=100)
    packaging_size = models.CharField(null=True, blank=True, max_length=100)

    orders_needed = models.IntegerField(default=5)
    orders = models.IntegerField(default=0)

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('bikes:details', kwargs={
            'type_pk': self.type_id,
            'bike_pk': self.id
        })

    def __str__(self):
        return self.name


class Order(models.Model):
    total_charge = MoneyField(max_digits=7,
                              decimal_places=2,
                              default_currency='USD'
                              )
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=254)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone Number")
    phone = models.CharField(max_length=17, validators=[phone_regex])

    def __str__(self):
        return self.name


class Billing(models.Model):
    DEFAULT_PK = 1
    user_info = models.ForeignKey(Order, default=DEFAULT_PK)
    state = USStateField()
    city = models.CharField(max_length=25)
    address = models.CharField(max_length=100)
    zip = USZipCodeField()

    def __str__(self):
        return self.address + ", " + self.city + ", " + self.state


class Card(models.Model):
    DEFAULT_PK = 1
    user_info = models.ForeignKey(Order, default=DEFAULT_PK)
    number = models.IntegerField("Credit Card Number")
    expiration = models.DateTimeField()
    ccv_number = models.IntegerField("CCV Number")
    # validators=([MaxValueValidator(9999)]))
    # , widget = forms.TextInput(attrs={'size': '4'})

    def __str__(self):
        stri = "{}".format(self.number)
        return "****-****-****-{}".format(stri[-4:])


class Preorders(models.Model):
    user_info = models.ForeignKey(Order)
    address = models.ForeignKey(Billing)
    payment = models.ForeignKey(Card)
    order = models.ForeignKey(Bikes)
    status = models.CharField(max_length=25, default="reserved")

    def __str__(self):
        return self.order.name


class Message(models.Model):
    user = models.ForeignKey(Order)
    message = models.TextField()
    owner = models.CharField(max_length=25, default="from")

    def __str__(self):
        return "{}".format(self.id)

Bikes/forms.py
from datetime import datetime

from django import forms
from django.contrib.auth.models import User

from Bikes import models, widgets


def get_cc_type(number):
    """
    Gets credit card type given number. Based on values from Wikipedia page/
    "Credit card number".
    http://en.wikipedia.org/w/index.php?title=Credit_card_number
       """
    number = str(number)
    # group checking by ascending length of number
    if len(number) == 13:
        if number[0] == "4":
            return "Visa"
    elif len(number) == 14:
        if number[:2] == "36":
            return "MasterCard"
    elif len(number) == 15:
        if number[:2] in ("34", "37"):
            return "American Express"
    elif len(number) == 16:
        if number[:4] == "6011":
            return "Discover"
        if number[:2] in ("51", "52", "53", "54", "55"):
            return "MasterCard"
        if number[0] == "4":
            return "Visa"
    return "Unknown"


def must_be_empty(value):
    """ raises Validation Error is field is not empty"""
    if value:
        raise forms.ValidationError('This field needs to be empty')


class PasswordForm(forms.Form):
    """ Form to put in password """
    password = forms.CharField(widget=forms.PasswordInput)
    verify_password = forms.CharField(max_length=20, label="Please verify your password", widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        verify_password = cleaned_data.get('verify_password')

        if password != verify_password:
            raise forms.ValidationError(
                "You need to enter the same password in 'password' and 'verify password' Fields"
            )

        if User.objects.filter(password=password).exists():
            raise forms.ValidationError(
                "Invalid password"
            )


class EditInfoForm(forms.ModelForm):
    """ Form to edit personal info """
    password = forms.CharField(widget=forms.PasswordInput, required=False)
    verify_password = forms.CharField(max_length=20, required=False, label="Please verify your password",
                                      widget=forms.PasswordInput)
    class Meta:
        model = models.Order
        fields = ['name', 'phone', 'email']

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        verify_password = cleaned_data.get('verify_password')

        if password != verify_password:
            raise forms.ValidationError(
                "You need to enter the same password in 'password' and 'verify password' fields"
            )

        if User.objects.filter(password=password).exists():
            raise forms.ValidationError(
                "Invalid password. Try another password."
            )


class OrderForm(forms.ModelForm):
    """ Form to register a new user """
    class Meta:
        model = models.Order
        fields = [
            'name',
            'phone',
            'email'
        ]

    verify_email = forms.EmailField(max_length=254, label="Please verify your email address")
    honeypot = forms.CharField(required=False,
                               widget=forms.HiddenInput,
                               label="leave empty",
                               validators=[must_be_empty],
                               )

    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get('name')
        verify = cleaned_data.get('verify_email')
        email = cleaned_data.get('email')
        phone = cleaned_data.get('phone')

        if email != verify:
            raise forms.ValidationError(
                "You need to enter the same email in both fields"
            )


class BillingForm(forms.ModelForm):
    """ Form to add address """
    class Meta:
        model = models.Billing
        fields = ['address', 'city', 'state', 'zip']

    honeypot = forms.CharField(required=False,
                               widget=forms.HiddenInput,
                               label="leave empty",
                               validators=[must_be_empty]
                               )

    def clean(self):
        cleaned_data = super().clean()
        state = cleaned_data.get('state')
        city = cleaned_data.get('city')
        address = cleaned_data.get('address')
        zip = cleaned_data.get('zip')


class CardForm(forms.ModelForm):
    """ Form to add a new credit card """
    ccv_number = forms.IntegerField(widget=forms.TextInput(attrs={'size': '4'}))
    expiration = forms.DateField(widget=widgets.MonthYearWidget())

    class Meta:
        model = models.Card
        fields = ['number', 'expiration', 'ccv_number']

    honeypot = forms.CharField(required=False,
                            widget=forms.HiddenInput,
                            label="leave empty",
                            validators=[must_be_empty],
                            )

    def clean(self):
        cleaned_data = super().clean()
        number = cleaned_data.get('number')
        expiration = cleaned_data.get('expiration')
        ccv_number = cleaned_data.get('ccv_number')

        if expiration <= datetime.now().date():
            raise forms.ValidationError(
                "Your credit card is expired."
            )

        if (number and (len(str(number)) < 13 or len(str(number)) > 16)) or (ccv_number and len(str(ccv_number)) > 4 ):
            raise forms.ValidationError(
                "Credit Card invalid!"
            )

        # elif get_cc_type(number) not in ("Visa", "MasterCard", "American Express"):
        #    raise forms.ValidationError("Please enter in a Visa, Master Card, or American Express credit card number.")

        # if ccv_number and len(str(ccv_number)) > 4:
        #     raise forms.ValidationError(
        #         "Credit"
        #     )


class SelectionForm(forms.Form):
    """ form to select cards or addresses of user """
    card = forms.ModelChoiceField(queryset=models.Card.objects.all(), empty_label=None)
    billing = forms.ModelChoiceField(queryset=models.Billing.objects.all(), empty_label=None)

    def clean(self):
        cleaned_data = super().clean()
        card = cleaned_data.get('card')
        billing = cleaned_data.get('billing')
    if not card:
        raise forms.ValidationError("YOu did not pick a valid credit card")

    if not billing:
        raise forms.ValidationError("You did not pick a valid address.")


# class BillSelectionForm(forms.Form):
#     """  """
#     billing = forms.ModelChoiceField(queryset=models.Billing.objects.all())
#
#     def clean(self):
#         cleaned_data = super().clean()
#         billing = cleaned_data.get('billing')
#
#
# class CardSelectionForm(forms.Form):
#     """  """
#     card = forms.ModelChoiceField(queryset=models.Card.objects.all())
#
#     def clean(self):
#         cleaned_data = super().clean()
#         card = cleaned_data.get('card')


class LoginForm(forms.Form):
    """ Form to login user """
    name = forms.CharField(max_length=100, label="Name")
    email = forms.EmailField(max_length=254, label="Email:")
    password = forms.CharField(widget=forms.PasswordInput)
    honeypot = forms.CharField(required=False,
                               widget=forms.HiddenInput,
                               label="leave empty",
                               validators=[must_be_empty],
                               )

    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get('name')
        email = cleaned_data.get('email')
        password = cleaned_data.get('password')


class MessageForm(forms.ModelForm):
    """ Form to send messages to staff """
    class Meta:
        model = models.Message
        fields = ['message']


class AmountForm(forms.Form):
    """ Form that takes the amount of the user """
    amount = forms.IntegerField()

    def clean(self):
        cleaned_data = super().clean()
        amount = cleaned_data.get('amount')

        if amount:
            if amount < 1:
                raise forms.ValidationError(
                    "You cant order zero or Negative amounts"
                )
        else:
            raise forms.ValidationError("Can't be empty")



# BillingFormSet = forms.modelformset_factory(
#     models.Billing,
#     form=BillingForm,
#     extra=1
# )
#
# CardFormSet = forms.modelformset_factory(
#     models.Card,
#     form=CardForm,
#     extra=1,
# )
#
# BillingInlineFormSet = forms.inlineformset_factory(
#     models.Order,
#     models.Billing,
#     extra=0,
#     fields=('state', 'city', 'address', 'zip'),
#     formset=BillingFormSet,
# )
#
# CardInlineFormSet = forms.inlineformset_factory(
#     models.Order,
#     models.Card,
#     extra=1,
#     fields=('number', 'expiration', 'ccv_number',),
#     formset=CardFormSet,
# )

Bikes/templates/Bikes/admin_users_orders.html
{% extends "layout.html" %}

{% load bikes_extras %}

{% block title %}{{ order.name }} orders{% endblock %}

{% block submenu %}{% endblock %}

{% block content %}
    <div class="row">
    <div class="col-sm-10 col-sm-offset-1">
        <h3>{{ order }}</h3>
        <p>Phone: {{ order.phone }}</p>
        <p>Email: {{ order.email }}</p>
        <p>Total charged:  {{ order.total_charge }}</p>
        <button class="dropdownform-button button">Message {{ order.name }}</button>
        <div class="inserted-form dropdownform" style="display: none">
        <h3>Send a message to {{ order.name }}:</h3>
        <form action="{% url 'bikes:admin_message' %}" method="POST" class="message-form">
            <textarea class="message" id="id_message" name="message" placeholder="send message to {{ order }}" required></textarea>
            <input type="hidden" name="pk" class="pk" value="order.pk">
            {% csrf_token %}
            <input type="submit" class="button" value="send">
        </form>
    </div>
    </div>
    <div class="row">
        {% if reservations %}

            <h3 class="mr-60">Reserved Bikes:</h3>
            {% get_status 'reserved' as status %}
            {% customers reservations as bike_orders %}
            {% include 'bikes/admin_user_template.html' %}

        {% endif %}
        {% if shipping %}

            <h3 class="mr-60">Bikes Ready to ship:</h3>
            {% get_status 'shipping' as status %}
            {% customers shipping as bike_orders %}
            {% include 'bikes/admin_user_template.html' %}

        {% endif %}
        {% if shipped %}
            <h3 class="mr-60">Bikes shipped: </h3>
            {% get_status 'shipped' as status %}
            {% customers shipped as bike_orders %}
            {% include 'bikes/admin_user_template.html' %}
        {% endif %}
    </div></div>
{% endblock %}

Bikes/templates/Bikes/all_orders.html
{% extends "layout.html" %}

{% block title %}Admin (all orders){% endblock %}

{% block content %}
    <div class="row">
        {% for order in orders %}
            {% if order.name != "Anonymous" %}
                <div class="col-sm-6 col-xs-10">
                    <div class="callout">
                        <h4>Name: {{ order.name }}</h4>
                            <p class="mb-5">Email: {{ order.email }}</p>
                            <p class="mb-5">Phone: {{ order.phone }}</p>
                            <p>total to charge: {{ order.total_charge }}</p>
                            <button class="dropdownform-button btn btn-primary">Message {{ order.name }}</button>
                            <div class="inserted-form dropdownform" style="display: none">
                                <h3>Send a message to {% if user.is_superuser %}
                                    <a href="{% url 'bikes:users_orders' pk=order.pk %}">{{ order.name }}</a>{% else %}
                                    us!{% endif %}</h3>
                                <form class="message-form" action="{% url 'bikes:admin_message' %}" method="POST">
                                    <textarea class="message" id="id_message" name="message" placeholder="send message to {{ order }}"
                                              required></textarea>
                                    <input type="hidden" name="pk" class="pk" value="{{ order.pk }}">
                                    {% csrf_token %}
                                    <input type="submit" class="button" value="send">
                                </form>
                            </div>
                            <a href="{% url 'bikes:users_orders' pk=order.pk %}"
                               class="button mt-10">See all orders from {{ order }}</a>

                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
{% endblock %}

Bikes/templates/Bikes/confirm_order.html
{% extends "cart/cart_chart.html" %}

{% block title %}Order {% endblock %}

{% block order_form %}
    <div class="row " xmlns="http://www.w3.org/1999/html">
        <div class="col-lg-6 col-sm-10 col-sm-offset-1 ">

            <div class="left">
                <h5>Make sure you look over your order before you confirm.</h5>
                <h4>Total charge: {{ total_amount }}</h4>
                <p>where to ship</p>
                <form action="" method="post">
                    <select class="element select small" id="mock-address" name=mock-address">
                        <option value="0" class="zero" selected="selected">----</option>
                        {% for address in addresses %}
                            <option class="zero" value="{{ address.pk }}">{{ address }}</option>
                        {% endfor %}
                        <input type="submit" value="add" style="display: none;">
                    </select>
                </form>

                <button type="button" class="button dropdownform-button">Add another address</button>
                <div class="inserted-form dropdownform add-address-form-div" style="display: none;">
                    <form action="{% url 'bikes:add_address' %}" class="add-address-form" method="POST">
                        {{ add_address }}
                        {% csrf_token %}
                        <input type="submit" class="button" value="add">
                    </form>
                </div>

            </div>
            <div class="right">

                <p>Credit Card</p>
                    <select id="mock-card" name="mock-card">
                        <option value="0" selected="selected">----</option>
                        {% for card in cards %}
                            <option value="{{ card.pk }}">{{ card }}</option>
                        {% endfor %}

                    </select>

                <button type="button" class="button dropdownform-button">Add another card</button>
                <div class="inserted-form dropdownform " style="display: none;">
                    <form class="add-card-form" action="{% url 'bikes:add_card' %}" method="POST">
                        <p><strong>WARNING! WARNING! WARING! Don't put in your real information.</strong> This is just a demo. Just put in any random 16 numbers and any random ccv number</p>
                        {{ add_card.as_p }}
                        {% csrf_token %}
                        <input type="submit" class="button" value="add">
                    </form>
                </div>
            </div>

            <div class="submit_seperator">
                <form action="" method="POST" id="main-form">
                    <div id="address-slot" style="display: none;">{{ form.billing }}</div>
                    <div id="card-slot" style="display: none;">{{ form.card }}</div>
                    {% csrf_token %}
                <input type="submit" class="button order-form-submit" name="Confirm Order">
                </form>
            </div>
    </div>
    </div>
{% endblock %}

Bikes/templates/Bikes/login.html
{%  extends "layout.html" %}

{% block title %}Login{% endblock %}

{% block submenu %}
    <li class="has-submenu"><a href="{% url 'bikes:type' %}">Bikes</a></li>
{% endblock %}

{% block content %}
    <div class="row columns">
        <h3>Login to be able to look and change your orders</h3>
        <p>You make an account by preordering a bike</p>
        <form action="" method="POST">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" class="button">
        </form>
    </div>
{% endblock %}

Bikes/templates/Bikes/order_details.html
{%  extends "bikes/detail_layout.html" %}

{% load bikes_extras %}

{% block title %}{{ bike}} orders{% endblock %}

<style>
{% block javascript %}

{% endblock %}
</style>

{% block orders %}
    {% orders_by_address orders users as addresses %}
    {% orders_by_card orders users as cards %}
    <div class="row">
    {% for address, amount in addresses.items %}
        <p>Planning to ship {{ amount }} to {{ address }}</p>
    {% endfor %}

    <div class="col-lg-8 col-sm-10 col-sm-offset-1">
    <div class="callout">
    <div class="">
    <div class="old-data">
    {% for address, amount in addresses.items %}
                <h3>{{ amount }} {{ bike }}'s is being shipped to <span id="address-title-{{ address.pk }}">{{ address }}</span>. </h3>
                <div class="x block">
                <div class="bill-form flex">
                <button class="btn btn-primary dropdownform-button">Edit Address</button>

                <div class="row columns  dropdownform">

                    {% get_bill_form address as bill_form %}
                    <form action="{% url 'bikes:edit_address' %}" method="POST"
                          class="edit-address-form inserted-form m-0">
                        <p>Edit this address and all order's with this address</p>
                        {{ bill_form.management_form }}
                        {{ bill_form.address }}
                        {{ bill_form.city }}
                        {{ bill_form.state }}
                        {{ bill_form.zip }}
                        <input type="hidden" name="pk" class="hidden-pk" value="{{ address.pk }}">
                        {% csrf_token %}
                        <input type="submit" class="btn btn-success mb-5"
                               value="edit address.">
                    </form>
                </div></div></div>
    {% endfor %}

    <!-- change addresses form -->
    <div class="change-bill mt-10 flex">
    <button class="btn btn-success dropdownform-button">Change Addresses</button>
    <form name="change-bill-form change-form" action="{% url 'bikes:change_address' %}" method="post"
          class="dropdownform change-bill-form inserted-form m-0">
        <div class="all-addresses-form" style="text-decoration: none;">
        <input type="hidden" name="orders" value="{% for address in orders %}{{ address.pk }} {% endfor %}">
        {% for address in orders %}
            <select name="billing{{ address.pk }}" class="billing select" id="billing-for-{{ address.pk }}">
                <option value="" selected="selected">-------</option>
                {% for bill in bills %}
                    <option value="{{ bill.pk }}">{{ bill }}</option>
                {% endfor %}
            </select>
        {% endfor %}
        {% csrf_token %}
        </div>
        <input type="submit" class="btn btn-info mb-10">
    </form>
    </div>

    <!-- Card charged -->
    {% for card, price in cards.items %}
        <h3>We will charge <span id="card-title-{{ card.pk }}">{{ card }}</span> {{ price }}!</h3>
        <div class="x block">
                <div class="bill-form flex" style="margin-bottom: 10px;">
                <button class="btn btn-primary dropdownform-button">Edit Card</button>
                <div class="row columns dropdownform">
                    {% get_card_form card as card_form %}
                    <form action="{% url 'bikes:edit_card' %}" method="POST"
                          class="edit-card-form inserted-form m-0">
                        <p>Edit this card and all order's with this card</p>
                        <p><strong>WARNING: Don't put in your real information.</strong> This is just a demo. Just put in any random 16 numbers and any random ccv number</p>
                        {{ card_form.management_form }}
                        {{ card_form.number }}
                        {{ card_form.expiration }}
                        {{ card_form.ccv_number }}
                        <input type="hidden" name="pk" class="pk" value="{{ card.pk }}">
                        {% csrf_token %}
                        <input type="submit" class="btn btn-success mb-5" value="edit cards">
                    </form>
                </div>
                </div></div>
    {% endfor %}
    <div class="change-card flex">

    <!-- Change cards form -->
    <button class="btn btn-success dropdownform-button">Change Cards</button>
    <form name="change-card-form" action="{% url 'bikes:change_card' %}" method="post"
          class="dropdownform inserted-form m-0 change-form">
        <div class="all-card-form" style="text-decoration: none;">
        <input type="hidden" name="orders" value="{% for card in orders %}{{ card.pk }} {% endfor %}">
        {% for order in orders %}
            <select name="card{{ order.pk }}" class="card select" id="card-for-{{ order.pk }}">
                <option value="" selected="selected">-------</option>
                {% for card in credit_cards %}
                    <option value="{{ card.pk }}">{{ card }}</option>
                {% endfor %}
            </select>
        {% endfor %}
        {% csrf_token %}
        </div>
        <input type="submit" class="btn btn-info mb-10">
    </form>
    </div></div>

    <!-- cancel form -->
    <h4 class="reload-page" style="display: none;">Reload the page to see changes </h4>
    <button class="btn btn-danger dropdownform-button mt-10 block">Cancel/Change Order</button>
        <table class="dropdownform no-overflow">
        <tr>
            <th>Product</th>
            <th>Address</th>
            <th>Card</th>
            <th>Remove</th>
        </tr>
        {% for item in orders %}
        <tr id="item-row-{{ item.pk }}">
            <td class="td-{{ item.pk }}"><a href="">{{ item.order }}</a></td>
            <td class="td-{{ item.pk }}">{{ item.address }}</td>
            <td class="td-{{ item.pk }}">{{ item.payment }}</td>
            <td class="td-{{ item.pk }}"><form method="post" action="{% url 'bikes:cancel' %}" class="cancel-order">
                <input type="hidden" class="pk" name="pk" value="{{ item.pk }}">
                {% csrf_token %}
                <input type="submit" class="button remove-item" value="X">
            </form></td>
        </tr>
        {% endfor %}
    </table>
    <form method="post" action="{% url 'bikes:cancel_all' %}" class="cancel-all-orders dropdownform">
        <input type="hidden" class="pk" name="pk" value="{{ bike.pk }}">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger cancel-all-orders-button" value="Cancel all orders">
    </form>

    </div>
    </div>
    </div>
    </div>

{% endblock %}