Bikes/urls.py
from django.conf.urls import url

from Bikes import views

urlpatterns = [
    url(r'^$', views.bike_type_list, name="type"),

    url(r'superuser/$', views.admin_orders, name="all_orders"),
    url(r'superuser/message/$', views.admin_send_message, name='admin_message'),
    url(r'superuser/ready to ship/$', views.orders_ready_to_ship, name="admin_shipping"),
    url(r'superuser/mark shipped/$', views.shipping_order, name="mark shipped"),
    url(r'superuser/received/(?P<pk>\d+)/$', views.recieved_order, name="recieved"), # login not working
    url(r'superuser/(?P<pk>\d+)/$', views.admin_user_preorders, name="users_orders"),
    # url(r'superuser/bike/(?P<pk>\d+)$', views.admin_orders_bike, name="bike_ordered"),
    url(r'superuser/change amount/$', views.change_reservation_amount, name="change_reservation_amount"),

    url(r'user/$', views.users_orders, name='user'),
    # url(r'user/ready/$', views.users_orders_ready, name='ready'),
    # url(r'user/ready/(?P<pk>\d+)/$', views.ready_order_details, name='shipping'),
    # url(r'user/shipped/(?P<pk>\d+)/$', views.sending_order_details, name='shipped'),
    url(r'user/edit address/$', views.edit_address, name='edit_address'),
    url(r'user/change address/$', views.change_address, name='change_address'),
    url(r'user/edit card/$', views.edit_card, name='edit_card'),
    url(r'user/change card/$', views.change_card, name='change_card'),
    # url(r'user/edit cards/$', views.edit_cards, name='edit_cards'),
    url(r'user/(?P<pk>\d+)/$', views.order_details, name='order_detail'),
    url(r'user/edit/$', views.edit_order, name='edit'),
    # url(r'user/change password/$', views.change_password, name='change_password'),
    url(r'user/cancel order/$', views.cancel_order, name='cancel'),
    url(r'user/cancel orders/$', views.cancel_all_orders, name='cancel_all'),
    url(r'user/add address/$', views.add_address, name="add_address"),
    url(r'user/add card/$', views.add_card, name="add_card"),

    url(r'first checkout/$', views.first_checkout, name='first_checkout'),
    url(r'checkout/$', views.checkout, name='checkout'),


    url(r'^(?P<types_pk>\d+)/(?P<bike_pk>\d+)/$', views.bike_details, name='details'),
    # url(r'(?P<types_pk>\d+)/(?P<bike_pk>\d+)/order/$', views.order_bike, name='order'),
    # url(r'(?P<types_pk>\d+)/(?P<bike_pk>\d+)/order more/$', views.order_another_bike, name='order_more'),
    url(r'^(?P<pk>\d+)/$', views.bike_list, name='list'),
]

EletricBikeReserving/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

from EletricBikeReserving import views
from shopping_cart.views import register

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', views.home, name='home'),
    url(r'login/$', views.loginer, name='login'),
    url(r'accounts/login/$', views.loginer, name='login'),
    url(r'logout/$', views.logout_view, name='logout'),
    url(r'^message/$', views.message, name="message"),
    url(r'^delete message/$', views.delete_message, name="delete"),
    url(r'register/(?P<pk>\d+)/$', register, name='register'),

    url(r'^bikes/', include('Bikes.urls', namespace='bikes')),
    url(r'^cart/', include('shopping_cart.urls', namespace='cart'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopping_cart/urls.py
from django.conf.urls import url

from shopping_cart import views

urlpatterns = [
    url(r'^$', views.show_cart, name='cart'),
    url(r'remove/$', views.remove_item_in_cart, name='remove'),
    # url(r'update cart/$', views.update_cart, name='update'),
    url(r'change amount/$', views.change_amount, name='change_amount'),
    url(r'(?P<pk>\d+)/$', views.add_to_cart, name='add_to_cart'),
]

shopping_cart/models.py
from django.db import models

# Create your models here.
from djmoney.models.fields import MoneyField

from Bikes.models import Order, Bikes


class Cart(models.Model):
    user = models.ForeignKey(Order)
    bike = models.ForeignKey(Bikes)
    quantity = models.PositiveIntegerField(default=1)
    price = MoneyField(max_digits=7,
                       decimal_places=2,
                       default_currency='USD',
                       )

    def __str__(self):
        return self.bike.name

shopping_cart/views.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, Http404, JsonResponse
from django.shortcuts import render, get_object_or_404, redirect

# Create your views here.
from django.urls import reverse

from Bikes.forms import AmountForm, OrderForm, PasswordForm
from Bikes.models import Order, Bikes
from shopping_cart import models


def email_name_unique(request, name, email, user=None):
    """makes sure email and password is unique"""
    users_email = User.objects.filter(email=email)
    users_name = User.objects.filter(username=name)
    if users_email and user not in users_email:
        messages.error(request, "This email is all ready used by another user")
        return False
    elif users_name and user not in users_name:
        messages.error(
            request,
            "This name is all ready used by another costomer"
        )
        return False
    else:
        return True


@login_required
def add_to_cart(request, pk, amount=None):
    """ Adds bike to cart """
    bike = get_object_or_404(Bikes, pk=pk)
    amount_form = AmountForm(request.POST, empty_permitted=True)
    user = Order.objects.get(name=request.user.username)
    print(amount)
    if amount_form.is_valid() and amount is None:
        amount = amount_form.cleaned_data.get('amount')
        try:
            int(amount)
            print("amount is specified it its {}".format(amount))
        except:
            print("amount not specified")
            amount = 1
    total_price = amount * bike.price
    if models.Cart.objects.filter(user=user).filter(bike=bike):
        cart = models.Cart.objects.filter(user=user).get(bike=bike)

        cart.quantity += amount
        cart.price += total_price
        cart.save()
        messages.success(request, "Added more bikes to cart")
    else:
        models.Cart.objects.create(user=user, bike=bike, quantity=amount, price=total_price)
        messages.success(request, "Added to cart")
    return HttpResponseRedirect(reverse('cart:cart'))



@login_required
def show_cart(request):
    """shows item in cart """
    user = Order.objects.get(name=request.user.username)
    cart = models.Cart.objects.filter(user=user)
    return render(request, 'cart/cart.html', {'cart': cart})


@login_required()
def remove_item_in_cart(request):
    """ removes one object from the cart that the user X'ed """
    pk = request.POST.get("pk")
    if not pk:
        return HttpResponseRedirect(reverse('cart:cart'))
    item = models.Cart.objects.get(pk=pk)
    if request.user.username != item.user.name:
        messages.error(request, "You cant delete that object its not in you cart")
        return redirect('/')
    item.delete(keep_parents=True)
    return HttpResponseRedirect(reverse('cart:cart'))


def register(request, pk):
    """ user registers and  than adds item to cart (For first time buyers that don't have an account)"""
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('bikes:type'))
    form = OrderForm(request.POST or None)
    password = PasswordForm(request.POST or None)
    bike = Bikes.objects.get(pk=pk)
    amount_form = AmountForm(request.POST, empty_permitted=True)
    if form.is_valid() and password.is_valid() and amount_form.is_valid() and email_name_unique(
            request, form.cleaned_data['name'], form.cleaned_data['email']):
        amount = amount_form.cleaned_data.get('amount')
        """if not amount:
            print(amount_form)
            for item in amount_form:
                print(item)
            raise Http404"""
        order = form.save(commit=False)
        order.total_charge = 0.00
        order.save()
        user = User.objects.create_user(
            form.cleaned_data['name'],
            form.cleaned_data['email'],
            password.cleaned_data['password']
        )
        login(request, user)
        print(amount)
        return add_to_cart(request, pk, amount)
    return render(request, 'cart/registation_form.html',
              {'form': form, 'password': password, 'bike': bike, 'amount': amount_form})


@login_required()
def change_amount(request):
    """ Changes amount of bikes in cart. """
    pk = request.POST.get('pk')
    if not pk:
        return HttpResponseRedirect(reverse('cart:cart'))
    item = models.Cart.objects.get(pk=pk)
    if request.user.username != item.user.name:
        messages.error(request, "You cant change value of this item its not in your cart")
        return redirect('/')
    bike = Bikes.objects.get(pk=item.bike_id)
    old_price = round(float(item.price) * 100)/100
    amount = AmountForm(request.POST)
    if amount.is_valid():
        total = bike.price * amount.cleaned_data.get('amount')
        item.quantity = amount.cleaned_data['amount']
        item.price = total
        item.save()
        if request.is_ajax():
            price = round(float(total) * 100)/100
            return JsonResponse({
                'price': price,
                'old_price': old_price,
                'amount': item.quantity,
            })
        else:
            messages.success(request, "changed amount")
    return HttpResponseRedirect(reverse('cart:cart'))


# @login_required()
# def update_cart(request):
#     """ update  """
#     user = Order.objects.get(name=request.user.username)
#     cart = models.Cart.objects.filter(user=user)
#     for item in cart:
#         bike = Bikes.objects.get(pk=item.bike_id)
#         amount = AmountForm(bike.name)
#         if amount.is_valid():
#             total = bike.price * amount.cleaned_data['amount']
#             item.quantity = amount.cleaned_data['amount']
#             item.price = total
#             item.save()
#     return HttpResponseRedirect(reverse('cart:cart'))

shopping_cart/templates/cart/cart.html
{% extends 'layout.html' %}

{% load cart_extras %}

{% block title %}Shopping Cart{% endblock %}

{% block content %}
    <div class="row">
    <div class="col-sm-10 col-sm-offset-1 shopping-cart-chart">
    {% if cart %}
    <table>
        <tr>
            <th>Product</th>
            <th>Quantity (update by pressing ENTER)</th>
            <th>Total Amount</th>
            <th>Remove</th>
        </tr>
        {% for item in cart %}
        <tr id="item-row-{{ item.pk }}">
            <td>
                <a href="{% url 'bikes:details' types_pk=item.bike.type.pk bike_pk=item.bike.pk %}">{{ item.bike }}</a>
            </td>
            <td><form method="POST" name="{{ item }}" action="{% url 'cart:change_amount' %}" class="sm-amount-form">
                {% csrf_token %}
                <input type="hidden" class="pk" name="pk" value="{{ item.pk }}">
                <input type="number" id="quantity-{{ item.pk }}" class="quantity" name="amount"
                       placeholder="{{ item.quantity }}" value="{{ item.quantity }}">
            </form></td>
            <td id="item-price-{{ item.pk }}">{{ item.price }}</td>
            <td><form method="post" action="{% url 'cart:remove' %}" class="remove-item-form">
                <input type="hidden" class="pk" name="pk" value="{{ item.pk }}">
                {% csrf_token %}
                <input type="submit" class="button remove-item" value="X">
            </form></td>
        </tr>
        {% endfor %}
    </table>
        {% total_charge cart as total_amount %}
        <h5>Total amount: <span class="total-amount">{{ total_amount }}</span></h5>
        <a href="{% url 'bikes:checkout' %}" class="button submit-all">Order now!</a>
    {% else %}
        <h3> Cart is empty </h3>
    {% endif %}
    </div>
    </div>
{% endblock %}

shopping_cart/templates/cart/cart_chart.html
{% extends "layout.html" %}

{% load cart_extras %}

{% block content %}

        <div class="row">
        <div class="col-sm-10 col-sm-offset-1">
        <table class="cart-table">
        <tr>
            <th>Product</th>
            <th>Quantity</th>
            <th>Total Amount</th>
        </tr>
        {% for item in cart %}
        <tr>
            <td>
                <a href="{% url 'bikes:details' types_pk=item.bike.type.pk bike_pk=item.bike.pk %}">{{ item.bike }}</a>
            </td>
            <td>{{ item.quantity }}</td>
            <td>{{ item.price }}</td>
        </tr>
        {% endfor %}
        </table>
    {% total_charge cart as total_amount %}
    </div></div>
    <div class="form_seperator">
        {% block order_form %}{% endblock %}
    </div>
{% endblock %}

shopping_cart/templates/cart/registation_form.html
{% extends "bikes/detail_layout.html" %}

{% block title %}Order an {{ bike.name }}!{% endblock %}

{% block details %}

    <div class="row columns">
        <h1>Amount {{ amount }}</h1>
        <h3>Already have an account: <a href="{% url 'login' %}">Login and order another</a></h3>
        <h3>Fill this out to register as a user</h3>
        <form action="" method="POST">
            <h4>Personal Info</h4>
            {{ form.as_p }}
            {% csrf_token %}
            {{ password.as_p }}
            <input type="submit" class="button">
        </form>
    </div>
{%  endblock %}