Bikes/urls.py
from django.conf.urls import url

from Bikes import views

urlpatterns = [
    url(r'^$', views.bike_type_list, name="type"),

    url(r'superuser/$', views.admin_orders, name="all_orders"),
    url(r'superuser/message/$', views.admin_send_message, name='admin_message'),
    url(r'superuser/ready to ship/$', views.orders_ready_to_ship, name="admin_shipping"),
    url(r'superuser/mark shipped/$', views.shipping_order, name="mark shipped"),
    url(r'superuser/received/(?P<pk>\d+)/$', views.recieved_order, name="recieved"), # login not working
    url(r'superuser/(?P<pk>\d+)/$', views.admin_user_preorders, name="users_orders"),
    # url(r'superuser/bike/(?P<pk>\d+)$', views.admin_orders_bike, name="bike_ordered"),
    url(r'superuser/change amount/$', views.change_reservation_amount, name="change_reservation_amount"),

    url(r'user/$', views.users_orders, name='user'),
    # url(r'user/ready/$', views.users_orders_ready, name='ready'),
    # url(r'user/ready/(?P<pk>\d+)/$', views.ready_order_details, name='shipping'),
    # url(r'user/shipped/(?P<pk>\d+)/$', views.sending_order_details, name='shipped'),
    url(r'user/edit address/$', views.edit_address, name='edit_address'),
    url(r'user/change address/$', views.change_address, name='change_address'),
    url(r'user/edit card/$', views.edit_card, name='edit_card'),
    url(r'user/change card/$', views.change_card, name='change_card'),
    # url(r'user/edit cards/$', views.edit_cards, name='edit_cards'),
    url(r'user/(?P<pk>\d+)/$', views.order_details, name='order_detail'),
    url(r'user/edit/$', views.edit_order, name='edit'),
    # url(r'user/change password/$', views.change_password, name='change_password'),
    url(r'user/cancel order/$', views.cancel_order, name='cancel'),
    url(r'user/cancel orders/$', views.cancel_all_orders, name='cancel_all'),
    url(r'user/add address/$', views.add_address, name="add_address"),
    url(r'user/add card/$', views.add_card, name="add_card"),

    url(r'first checkout/$', views.first_checkout, name='first_checkout'),
    url(r'checkout/$', views.checkout, name='checkout'),


    url(r'^(?P<types_pk>\d+)/(?P<bike_pk>\d+)/$', views.bike_details, name='details'),
    # url(r'(?P<types_pk>\d+)/(?P<bike_pk>\d+)/order/$', views.order_bike, name='order'),
    # url(r'(?P<types_pk>\d+)/(?P<bike_pk>\d+)/order more/$', views.order_another_bike, name='order_more'),
    url(r'^(?P<pk>\d+)/$', views.bike_list, name='list'),
]

EletricBikeReserving/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

from EletricBikeReserving import views
from shopping_cart.views import register

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', views.home, name='home'),
    url(r'login/$', views.loginer, name='login'),
    url(r'accounts/login/$', views.loginer, name='login'),
    url(r'logout/$', views.logout_view, name='logout'),
    url(r'^message/$', views.message, name="message"),
    url(r'^delete message/$', views.delete_message, name="delete"),
    url(r'register/(?P<pk>\d+)/$', register, name='register'),

    url(r'^bikes/', include('Bikes.urls', namespace='bikes')),
    url(r'^cart/', include('shopping_cart.urls', namespace='cart'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopping_cart/urls.py
from django.conf.urls import url

from shopping_cart import views

urlpatterns = [
    url(r'^$', views.show_cart, name='cart'),
    url(r'remove/$', views.remove_item_in_cart, name='remove'),
    # url(r'update cart/$', views.update_cart, name='update'),
    url(r'change amount/$', views.change_amount, name='change_amount'),
    url(r'(?P<pk>\d+)/$', views.add_to_cart, name='add_to_cart'),
]

Bikes/models.py
from django.core.validators import RegexValidator
from django.db import models
from djmoney.models.fields import MoneyField

# Create your models here.
from localflavor.us.models import USStateField, USZipCodeField


class BikeTypes(models.Model):
    type = models.CharField(max_length=100)
    picture = models.ImageField(upload_to='images')

    def __str__(self):
        return self.type


class Bikes(models.Model):
    type = models.ForeignKey(BikeTypes)
    name = models.CharField(max_length=100)
    picture = models.ImageField()
    description = models.TextField()
    price = MoneyField(max_digits=7,
                       decimal_places=2,
                       default_currency='USD',
                       )

    motor = models.CharField(null=True, blank=True, max_length=100)
    battery = models.CharField(null=True, blank=True, max_length=100)
    PAS = models.CharField(null=True, blank=True, max_length=100)
    controller = models.CharField(null=True, blank=True, max_length=100)
    charger = models.CharField(null=True, blank=True, max_length=100)
    charging_time = models.CharField(null=True, blank=True, max_length=100)

    max_speed = models.IntegerField(null=True, blank=True)
    range = models.IntegerField(null=True, blank=True)
    max_load = models.FloatField(null=True, blank=True)
    net_weight = models.FloatField(null=True, blank=True)
    gross_weight = models.FloatField(null=True, blank=True)
    container_load = models.FloatField(null=True, blank=True)
    display = models.CharField(null=True, blank=True, max_length=100)

    frame = models.CharField(null=True, blank=True, max_length=100)
    tyres = models.CharField(null=True, blank=True, max_length=100)
    rim = models.CharField(null=True, blank=True, max_length=100)
    front_fork = models.CharField(null=True, blank=True, max_length=100)
    front_brake = models.CharField(null=True, blank=True, max_length=100)
    rear_break = models.CharField(null=True, blank=True, max_length=100)
    speed = models.IntegerField(null=True, blank=True)
    derailleur = models.CharField(null=True, blank=True, max_length=100)
    stem = models.CharField(null=True, blank=True, max_length=100)
    brake_lever = models.CharField(null=True, blank=True, max_length=100)
    chain = models.CharField(null=True, blank=True, max_length=100)
    chain_wheel = models.CharField(null=True, blank=True, max_length=100)
    mudguard = models.CharField(null=True, blank=True, max_length=100)
    saddle = models.CharField(null=True, blank=True, max_length=100)
    pedal = models.CharField(null=True, blank=True, max_length=100)
    packaging_size = models.CharField(null=True, blank=True, max_length=100)

    orders_needed = models.IntegerField(default=5)
    orders = models.IntegerField(default=0)

    def get_absolute_url(self):
        from django.core.urlresolvers import reverse
        return reverse('bikes:details', kwargs={
            'type_pk': self.type_id,
            'bike_pk': self.id
        })

    def __str__(self):
        return self.name


class Order(models.Model):
    total_charge = MoneyField(max_digits=7,
                              decimal_places=2,
                              default_currency='USD'
                              )
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=254)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone Number")
    phone = models.CharField(max_length=17, validators=[phone_regex])

    def __str__(self):
        return self.name


class Billing(models.Model):
    DEFAULT_PK = 1
    user_info = models.ForeignKey(Order, default=DEFAULT_PK)
    state = USStateField()
    city = models.CharField(max_length=25)
    address = models.CharField(max_length=100)
    zip = USZipCodeField()

    def __str__(self):
        return self.address + ", " + self.city + ", " + self.state


class Card(models.Model):
    DEFAULT_PK = 1
    user_info = models.ForeignKey(Order, default=DEFAULT_PK)
    number = models.IntegerField("Credit Card Number")
    expiration = models.DateTimeField()
    ccv_number = models.IntegerField("CCV Number")
    # validators=([MaxValueValidator(9999)]))
    # , widget = forms.TextInput(attrs={'size': '4'})

    def __str__(self):
        stri = "{}".format(self.number)
        return "****-****-****-{}".format(stri[-4:])


class Preorders(models.Model):
    user_info = models.ForeignKey(Order)
    address = models.ForeignKey(Billing)
    payment = models.ForeignKey(Card)
    order = models.ForeignKey(Bikes)
    status = models.CharField(max_length=25, default="reserved")

    def __str__(self):
        return self.order.name


class Message(models.Model):
    user = models.ForeignKey(Order)
    message = models.TextField()
    owner = models.CharField(max_length=25, default="from")

    def __str__(self):
        return "{}".format(self.id)

Bikes/forms.py
from datetime import datetime

from django import forms
from django.contrib.auth.models import User

from Bikes import models, widgets


def get_cc_type(number):
    """
    Gets credit card type given number. Based on values from Wikipedia page/
    "Credit card number".
    http://en.wikipedia.org/w/index.php?title=Credit_card_number
       """
    number = str(number)
    # group checking by ascending length of number
    if len(number) == 13:
        if number[0] == "4":
            return "Visa"
    elif len(number) == 14:
        if number[:2] == "36":
            return "MasterCard"
    elif len(number) == 15:
        if number[:2] in ("34", "37"):
            return "American Express"
    elif len(number) == 16:
        if number[:4] == "6011":
            return "Discover"
        if number[:2] in ("51", "52", "53", "54", "55"):
            return "MasterCard"
        if number[0] == "4":
            return "Visa"
    return "Unknown"


def must_be_empty(value):
    """ raises Validation Error is field is not empty"""
    if value:
        raise forms.ValidationError('This field needs to be empty')


class PasswordForm(forms.Form):
    """ Form to put in password """
    password = forms.CharField(widget=forms.PasswordInput)
    verify_password = forms.CharField(max_length=20, label="Please verify your password", widget=forms.PasswordInput)

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        verify_password = cleaned_data.get('verify_password')

        if password != verify_password:
            raise forms.ValidationError(
                "You need to enter the same password in 'password' and 'verify password' Fields"
            )

        if User.objects.filter(password=password).exists():
            raise forms.ValidationError(
                "Invalid password"
            )


class EditInfoForm(forms.ModelForm):
    """ Form to edit personal info """
    password = forms.CharField(widget=forms.PasswordInput, required=False)
    verify_password = forms.CharField(max_length=20, required=False, label="Please verify your password",
                                      widget=forms.PasswordInput)
    class Meta:
        model = models.Order
        fields = ['name', 'phone', 'email']

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        verify_password = cleaned_data.get('verify_password')

        if password != verify_password:
            raise forms.ValidationError(
                "You need to enter the same password in 'password' and 'verify password' fields"
            )

        if User.objects.filter(password=password).exists():
            raise forms.ValidationError(
                "Invalid password. Try another password."
            )


class OrderForm(forms.ModelForm):
    """ Form to register a new user """
    class Meta:
        model = models.Order
        fields = [
            'name',
            'phone',
            'email'
        ]

    verify_email = forms.EmailField(max_length=254, label="Please verify your email address")
    honeypot = forms.CharField(required=False,
                               widget=forms.HiddenInput,
                               label="leave empty",
                               validators=[must_be_empty],
                               )

    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get('name')
        verify = cleaned_data.get('verify_email')
        email = cleaned_data.get('email')
        phone = cleaned_data.get('phone')

        if email != verify:
            raise forms.ValidationError(
                "You need to enter the same email in both fields"
            )


class BillingForm(forms.ModelForm):
    """ Form to add address """
    class Meta:
        model = models.Billing
        fields = ['address', 'city', 'state', 'zip']

    honeypot = forms.CharField(required=False,
                               widget=forms.HiddenInput,
                               label="leave empty",
                               validators=[must_be_empty]
                               )

    def clean(self):
        cleaned_data = super().clean()
        state = cleaned_data.get('state')
        city = cleaned_data.get('city')
        address = cleaned_data.get('address')
        zip = cleaned_data.get('zip')


class CardForm(forms.ModelForm):
    """ Form to add a new credit card """
    ccv_number = forms.IntegerField(widget=forms.TextInput(attrs={'size': '4'}))
    expiration = forms.DateField(widget=widgets.MonthYearWidget())

    class Meta:
        model = models.Card
        fields = ['number', 'expiration', 'ccv_number']

    honeypot = forms.CharField(required=False,
                            widget=forms.HiddenInput,
                            label="leave empty",
                            validators=[must_be_empty],
                            )

    def clean(self):
        cleaned_data = super().clean()
        number = cleaned_data.get('number')
        expiration = cleaned_data.get('expiration')
        ccv_number = cleaned_data.get('ccv_number')

        if expiration <= datetime.now().date():
            raise forms.ValidationError(
                "Your credit card is expired."
            )

        if (number and (len(str(number)) < 13 or len(str(number)) > 16)) or (ccv_number and len(str(ccv_number)) > 4 ):
            raise forms.ValidationError(
                "Credit Card invalid!"
            )

        # elif get_cc_type(number) not in ("Visa", "MasterCard", "American Express"):
        #    raise forms.ValidationError("Please enter in a Visa, Master Card, or American Express credit card number.")

        # if ccv_number and len(str(ccv_number)) > 4:
        #     raise forms.ValidationError(
        #         "Credit"
        #     )


class SelectionForm(forms.Form):
    """ form to select cards or addresses of user """
    card = forms.ModelChoiceField(queryset=models.Card.objects.all(), empty_label=None)
    billing = forms.ModelChoiceField(queryset=models.Billing.objects.all(), empty_label=None)

    def clean(self):
        cleaned_data = super().clean()
        card = cleaned_data.get('card')
        billing = cleaned_data.get('billing')
    if not card:
        raise forms.ValidationError("YOu did not pick a valid credit card")

    if not billing:
        raise forms.ValidationError("You did not pick a valid address.")


# class BillSelectionForm(forms.Form):
#     """  """
#     billing = forms.ModelChoiceField(queryset=models.Billing.objects.all())
#
#     def clean(self):
#         cleaned_data = super().clean()
#         billing = cleaned_data.get('billing')
#
#
# class CardSelectionForm(forms.Form):
#     """  """
#     card = forms.ModelChoiceField(queryset=models.Card.objects.all())
#
#     def clean(self):
#         cleaned_data = super().clean()
#         card = cleaned_data.get('card')


class LoginForm(forms.Form):
    """ Form to login user """
    name = forms.CharField(max_length=100, label="Name")
    email = forms.EmailField(max_length=254, label="Email:")
    password = forms.CharField(widget=forms.PasswordInput)
    honeypot = forms.CharField(required=False,
                               widget=forms.HiddenInput,
                               label="leave empty",
                               validators=[must_be_empty],
                               )

    def clean(self):
        cleaned_data = super().clean()
        name = cleaned_data.get('name')
        email = cleaned_data.get('email')
        password = cleaned_data.get('password')


class MessageForm(forms.ModelForm):
    """ Form to send messages to staff """
    class Meta:
        model = models.Message
        fields = ['message']


class AmountForm(forms.Form):
    """ Form that takes the amount of the user """
    amount = forms.IntegerField()

    def clean(self):
        cleaned_data = super().clean()
        amount = cleaned_data.get('amount')

        if amount:
            if amount < 1:
                raise forms.ValidationError(
                    "You cant order zero or Negative amounts"
                )
        else:
            raise forms.ValidationError("Can't be empty")



# BillingFormSet = forms.modelformset_factory(
#     models.Billing,
#     form=BillingForm,
#     extra=1
# )
#
# CardFormSet = forms.modelformset_factory(
#     models.Card,
#     form=CardForm,
#     extra=1,
# )
#
# BillingInlineFormSet = forms.inlineformset_factory(
#     models.Order,
#     models.Billing,
#     extra=0,
#     fields=('state', 'city', 'address', 'zip'),
#     formset=BillingFormSet,
# )
#
# CardInlineFormSet = forms.inlineformset_factory(
#     models.Order,
#     models.Card,
#     extra=1,
#     fields=('number', 'expiration', 'ccv_number',),
#     formset=CardFormSet,
# )

templates/ajax.html
<script class="ajax-page">
    $(document).ready(function() {
        $(".order-form-submit").click(function(event) {
            event.preventDefault();
            console.log("Forms ready to submit");
            var address = $("#mock-address").val();
            var card = $('select[name=mock-card] option:selected').val();
            $("#address-slot").children("#id_billing").val(address);
            $("#card-slot").children("#id_card").val(card);
            $(this).parent("#main-form").submit();
            console.log("Forms submitted");
        });

        console.log("AJAX in line");

        $(".add-card-form").submit(function(event) {
            // adds credit card
            event.preventDefault();
            formData = $(this).serialize();
            $.ajax({
                type: "POST",
                url: "{% url 'bikes:add_card' %}",
                data: formData,
                success: function(data) {
                    if (data.error) {
                        alert(data.error);
                    } else {
                        alert("card_added");
                        console.log(data);
                        newCard = '<option value="' + data.pk + '" selected>' + data.new_text + '</option>';
                        $("#mock-card").prepend(newCard);
                        $("#id_card").prepend(newCard);
                        $(".new-card").text(data.new_text).show();
                        $(".add-card-form-div").hide();
                        $(".add-card-form").val("");
                    }
                },
                error: function(error) {
                    alert("Need to reload page!");
                    // $(this).submit();
                }
            })
        });

        $(".add-address-form").submit(function(event) {
            // add's an address
            event.preventDefault();
            formData = $(this).serialize();
            zipCode = $(this).children("#id_zip").val();
            if (zipCode.length != 5 && zipCode.length != 10) {
                alert("Enter a zip code in the format XXXXX or XXXXX-XXXX.");
            } else {
            $.ajax({
                type: "POST",
                url: "{% url 'bikes:add_address' %}",
                data: formData,
                success: function(data) {
                    alert("address added");
                    console.log(data);
                    newAddress = '<option value="' + data.pk + '" selected>' + data.new_text + '</option>';
                    $("#mock-address").prepend(newAddress);
                    $("#id_billing").prepend(newAddress);
                    $(".new-address").text(data.new_text).show();
                    $(".add-address-form-div").hide();
                    $(".add-address-form").val("");

                },
                error: function(error) {
                    // alert("Need to reload page.");
                    // $(this).submit();
                }
            })
            }
        });

        // cart.html
        function transferToFloat(total) {
            // removes the $ and the , from price to be able to convert it into a float
            new_total = "";
            for (i=0; i < 20; i++) {
                asd = total.substring(i, i+1);
                if (asd != "$" && asd != ",") {
                    new_total += asd;
                }
            }
            new_total = parseFloat(new_total);
            return new_total;
        }

        $(".sm-amount-form").submit(function(event) {
            // changes amount on cart
            event.preventDefault();

            formData = $(this).serialize();
            pk = $(this).children('.pk').val();
            num = $(this).children(".quantity").val();
            if (num && num > 0) {
            $.ajax({
                type: "POST",
                url: "{% url 'cart:change_amount' %}",
                data: formData,
                success: function(data) {

                    price = data.price;
                    $('#item-price-'+pk).text('$' + price + '.00');
                    $("#quantity-"+pk).attr("placeholder", data.amount);
                    total = $(".total-amount").text();
                    new_total = transferToFloat(total);
                    console.log(new_total);
                    new_total = new_total - data.old_price + data.price;
                    $(".total-amount").text("$" + new_total + ".00");
                    alert("Amount changed");
                },
                error: function (error) {
                    // $(this).submit();
                }
            })
            } else {
                alert("YOu must add in a positive number.")
            }
        });

        $(".remove-item-form").submit(function(event) {
            // removes item from cart
            event.preventDefault();
            pk = $(this).children(".pk").val();
            formData = $(this).serialize();
            value = $("#item-price-"+pk).text();
            value = transferToFloat(value);
            total = $(".total-amount").text();
            total = transferToFloat(total);
            new_total = total - value;
            $.ajax({
                type: 'POST',
                data: formData,
                url: "{% url 'cart:remove' %}",
                success: function(data) {
                    alert("removed");
                    $("#item-row-"+pk).remove();
                    $(".total-amount").text("$" + new_total + '.00');
                },
                error: function(error) {
                    // $(this).submit();
                }
            })
        });

        // edit_orders.html
        $(".edit-address-form").submit(function(event) {
            // edit address
            event.preventDefault();
            formData = $(this).serialize();
            $Form = $(this);
            pk = $(this).children(".hidden-pk").val();
            zipCode = $(this).children("#id_zip").val();
            if (zipCode.length != 5 && zipCode.length != 10) {
                alert("Enter a zip code in the format XXXXX or XXXXX-XXXX.");
            } else {
            // Error with Zip message: ()
                $.ajax({
                    type: 'POST',
                    data: formData,
                    url:  "{% url 'bikes:edit_address' %}",
                    success: function(data) {
                        $Form.parent().hide();
                        $("#address-button-"+pk).text(data.text);
                        $("#address-title-"+pk).text(data.text);
                        alert("address edited");
                    },
                    error: function(error) {
                        $Form.submit();
                    }
                })
            }
        });

        $(".edit-card-form").submit(function(event) {
            // ajax request for edited credit card info
            event.preventDefault();
            formData = $(this).serialize();
            $form = $(this).parent();
            pk = $(this).children(".pk").val();
            $.ajax({
                type: 'POST',
                data: formData,
                url: "{% url 'bikes:edit_card' %}",
                success: function(data) {
                    if (data.error == "good") {
                        $form.hide();
                        $("#card-button-" + pk).text(data.card);
                        $("#card-title-"+pk).text(data.card);
                        alert("Card info edited!");
                    } else {
                        alert(data.error);
                    }
                },
                error: function(error) {
                    // $(this).submit();
                }
            })
        });

        // messages
        $(".delete-message").submit(function(event) {
            // ajax request to delete message
            event.preventDefault();
            formData = $(this).serialize();
            pk = $(this).children(".pk").val();

            $.ajax({
                type: 'POST',
                data: formData,
                url: "{% url 'delete' %}",
                success: function(data) {
                    $("#message-"+pk).hide();
                    alert("Message Deleted");
                },
                error: function(error) {
                    // $(this).submit();
                }
            })
        });

        // order_detail.html
        $firstAddrress = $(".all-addresses-form").children(".billing").first();
        $firstAddrress.change(function() {
            // alert($firstAddrress.val());
            $(".billing").val($firstAddrress.val());
            // $("#id_billing option:selected");
        });

        $firstCard = $(".all-card-form").children(".card").first();
        $firstCard.change(function() {
            // alert($firstCard.val());
            $(".card").val($firstCard.val());
            // $("#id_billing option:selected");
        });



        $(".cancel-order").submit(function(event) {
            // ajax request to cancel pacific order
            event.preventDefault();
            formData = $(this).serialize();
            pk = $(this).children(".pk").val();
            if (window.confirm("Are you sure you want to cancel your reservation?") == true) {
                $.ajax({
                    type: "POST",
                    data: formData,
                    url: "{% url 'bikes:cancel' %}",
                    success: function(data) {
                        newText = "<td class='new-item-td'>Item was removed</td>";
                        $("#item-row-"+pk).html(newText);
                        $(".dropdownform-button").hide();
                        $(".old-data").hide();
                        if (data.length == 0) {
                            location.reload();
                        }
                        alert("item deleted");
                        $(".reload-page").show();
                    },
                    error: function(error) {
                        // $(this).submit();
                    }
                });
            }
        });

        $(".cancel-all-orders-button").click(function(event) {
            event.preventDefault();
            if (window.confirm("Are you sure you want to cancel all orders?") == true) {
                $(".cancel-all-orders").submit();
            }
        });

        // admin - message form
        $(".change-reservation-amount").submit(function(event) {
            // change reservation
            event.preventDefault();
            formData = $(this).serialize();
            $pk = $(this).children(".pk");
            $input = $(this).children("p").children(".amount");
            amount = $input.val();
            orders = $(this).children(".amount-orders").val();
            newMore = parseInt(amount)  - parseInt(orders);
            good = true;
            if (newMore < 0) {
                good = confirm("We will have to ship to more than we have");
            }
            if (good) {
            $.ajax({
                type: "POST",
                data: formData,
                url: "{% url 'bikes:change_reservation_amount' %}",
                success: function(data){
                    $("#orders-needed").text(amount);
                    $input.attr("placeholder", amount);
                    if (newMore < 1) {
                        $("#order-p").hide();
                    } else {
                        $("#orders-left").text(newMore);
                    }
                    alert("Value changed");
                },
                error: function(error) {
                    alert("ERRER");
                }
            });
            }
        });

        $(".message-form").submit(function(event) {
            event.preventDefault();
            formData = $(this).serialize();
            $form = $(this);
            $.ajax({
                type: "POST",
                data: formData,
                url: "{% url 'bikes:admin_message' %}",
                success: function(data) {
                    $form.children(".message").val("");
                    $form.parents(".dropdownform").hide();
                    alert("Message sent");
                },
                error: function(error) {
                    alert("Message not sent");
                }
            });
        });

        $(".mark-shipped-form").submit(function(event) {
            // mark shipped
            event.preventDefault();
            formData = $(this).serialize();
            $form = $(this);
            $bike = $(this).children(".bike").val();
            $user = $(this).children(".user").val();
            $.ajax({
                type: "POST",
                data: formData,
                url: "{% url 'bikes:mark shipped' %}",
                success: function(data) {
                    alert("Marked as shipped!");
                    alert(data.users);
                    alert(data.bikes);
                    if (data.users == false && data.bikes == false) {
                        $form.parents(".user-box").hide();
                    } else if (data.bikes == false) {
                        $form.parents(".bike-box").hide();
                    } else {
                        $form.parents(".address").hide();
                        $(".card-"+$user+"-"+$bike).hide();
                        for (key in data.cards) {
                            value = data.cards[key];
                            alert("KEY: " + key + ", VALUE: " + data.cards[key]);
                            $("#card-"+key).show();
                            $("#card-"+key).children("span").text("$500");

                        }
                    }
                },
                error: function(error) {
                    alert("Error with ajax");
                }
            });
        });
    });
</script>